### ISSUE TITLE
Fast-running LFO

### ISSUE THREAD

**Issue by brampling** [awonak/UncertaintyGo#5]
I flashed a new out of the box Uncertainty with the LFO code. With 0V on the CV it's running significantly faster than shown in your demo, the slowest port is around 1 Hz. Adding CV speeds it up as expected.

Any idea why? Did you make any changes to the CPU frequency on your demo module?

**Comment by awonak** [comment]
I just tested the LFO firmware with the [uncertainty-v0.2.0-alpha2_lfo.uf2](https://github.com/awonak/UncertaintyGo/releases/download/v0.2.0-alpha2/uncertainty-v0.2.0-alpha2_lfo.uf2) version and I am getting the same faster rates than what's demonstrated on the video. I must have changed something in the script or firmware that changed the speed. I agree it's faster than it should be. I'll dig thought my change history to see if we can get it back to a more reasonable speed range for longer slow LFO periods.

**Comment by awonak** [comment]
I found the culprit! https://github.com/awonak/UncertaintyGo/commit/9a515dc158decd5209750945cb66321f682cda28#r117188835

I had reduced the number of times the firmware samples analog input when reading the cv input to improve performance, and it looks like I improved it too much! To get the LFO back to its previous desirable speed, I introduced a tiny sleep between cv changes to uniformly slow down the LFO rates.

You can get the latest version of the hotfix script on the release page: https://github.com/awonak/UncertaintyGo/releases/tag/v0.2.1

Thanks for using my firmware and for providing the feedback.

I'm going to mark this as closed. Feel free to reopen or make a new issue if you have any further observations.
